### ISSUE TITLE
Create asset not working

### ISSUE THREAD

**Issue by future-is-present** [bigchaindb/tutorial-crab#11] opened 2018-01-31 09:29 UTC
Trying to create an asset, when I click on `Execute code` I get the following response

```
Something went wrong!

Network request failed
```
References to IPDB have been changed to BigchainDB test network, but it seems not working

**Comment by jernejpregelj** [comment] 2018-01-31 09:32
@shahbazn This is possible problem with proxy code that adds auth headers

**Comment by shahbazn** [comment] 2018-01-31 11:09
@manolodewiner can you please add steps to reproduce exactly what are you trying to do i just posted a transaction with python driver and it went through just fine.

**Comment by future-is-present** [comment] 2018-02-01 09:02
@shahbazn As you can see I created this issue under the tutorial-crab repository. That means that the create asset that is failing and the button `Execute code` is in the tutorial crab website:
1. Go to 
https://tutorials.bigchaindb.com/crab
2. Scroll down and click on `First step: Create an asset`
3. Click on execute code

**Comment by shahbazn** [comment] 2018-02-01 10:44
@manolodewiner thanks for the info i checked and as @jernejpregelj mentioned its a config issue with nginx proxy will fix

**Comment by jernejpregelj** [comment] 2018-07-19 12:13
Closing since this is not relevant anymore.

**Closed as completed by jernejpregelj** 2018-07-19 12:13 UTC
